# Generated by Django 6.0 on 2025-12-08 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='interview_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='interview_mode',
            field=models.CharField(blank=True, choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=50),
        ),
        migrations.AddField(
            model_name='applicant',
            name='interview_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
