# Generated by Django 6.0 on 2025-12-08 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_applicant_interview_date_applicant_interview_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='interview_date',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='interview_mode',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='interview_time',
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.DateField()),
                ('interview_time', models.TimeField()),
                ('interview_mode', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=50)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('No Show', 'No Show')], default='Scheduled', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='myapp.applicant')),
            ],
            options={
                'ordering': ['-interview_date', '-interview_time'],
            },
        ),
    ]
