# Generated by Django 6.0 on 2025-12-09 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_applicant_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='role',
            field=models.CharField(choices=[('Candidate', 'Candidate'), ('HR', 'HR')], default='Candidate', max_length=20),
        ),
    ]
