# Generated by Django 6.0 on 2025-12-09 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_accesslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(choices=[('hyderabad', 'Hyderabad'), ('bangalore', 'Bangalore'), ('chennai', 'Chennai'), ('mumbai', 'Mumbai')], max_length=50)),
                ('job_type', models.CharField(choices=[('full-time', 'Full-Time'), ('part-time', 'Part-Time'), ('internship', 'Internship')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=100)),
                ('candidate_email', models.EmailField(max_length=254)),
                ('candidate_phone', models.CharField(max_length=15)),
                ('interview_type', models.CharField(choices=[('technical', 'Technical'), ('hr', 'HR'), ('general', 'General'), ('final', 'Final Round')], max_length=20)),
                ('interview_date', models.DateField()),
                ('interview_time', models.TimeField()),
                ('interviewer_name', models.CharField(max_length=100)),
                ('interviewer_email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='myapp.joblisting')),
            ],
            options={
                'ordering': ['-interview_date', '-interview_time'],
            },
        ),
    ]
