# Generated by Django 6.0 on 2025-12-09 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_joblisting_interviewschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.CharField(choices=[('Applied', 'Applied'), ('Reviewing', 'Reviewing'), ('Shortlisted', 'Shortlisted'), ('Interview Scheduled', 'Interview Scheduled'), ('Selected', 'Selected'), ('Rejected', 'Rejected')], default='Applied', max_length=50)),
                ('position_applied', models.CharField(blank=True, max_length=150)),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('interview_scheduled', models.BooleanField(default=False)),
                ('interview_date', models.DateField(blank=True, null=True)),
                ('interview_time', models.TimeField(blank=True, null=True)),
                ('interview_mode', models.CharField(blank=True, max_length=50)),
                ('interview_notes', models.TextField(blank=True)),
                ('selection_message', models.TextField(blank=True)),
                ('applicant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_status', to='myapp.applicant')),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status_report', to='myapp.signup')),
            ],
            options={
                'ordering': ['-last_updated'],
            },
        ),
    ]
